#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
MotorD = Spinning Test motor
MotorE = Right side drive motors
MotorF = Left side drive motors
MotorG = Flywheel Motors
*/

#include "JoystickDriver.c"

// VARIABLES
bool GOALLATCH_latchDown = false;

// CONSTANTS
int DRIVING_joystickDeadzone = 15;
int FLYWHEEL_onSpeed = 100;
int FLYWHEEL_offSpeed = 0;
int BALLCOLLECTION_onSpeed = 75;
int BALLCOLLECTION_offSpeed = 0;
int GOALLATCH_upPosition = 0;
int GOALLATCH_downPosition = 100;

task main()
{
  while(true)
  {
    getJoystickSettings(joystick);

    // DRIVING CONTROLS
    if(abs(joystick.joy1_y2) > DRIVING_joystickDeadzone) { // joystick.joy1_y2 is the y-axis on the right analog stick
    	motor[motorE] = joystick.joy1_y2; // joystick.joy1_y2 is the y-axis on the right analog stick
 		}
 		else {
 			motor[motorE] = 0;
		}
		if(abs(joystick.joy1_y1) > DRIVING_joystickDeadzone) { // joystick.joy1_y1 is the y-axis on the left analog stick
			motor[motorF] = joystick.joy1_y1; // joystick.joy1_y1 is the y-axis on the left analog stick
		}
		else {
			motor[motorF] = 0;
  	}

    // FLYWHEEL CONTROLS  	
  	if(joy1Btn(8)) { // joy1Btn(8) is the left trigger
  		motor[motorG] = FLYWHEEL_onSpeed; // motor[motorG] is the flywheel
  	}
  	else {
  		motor[motorG] = FLYWHEEL_offSpeed; // motor[motorG] is the flywheel
  	}

  	// BALL COLLECTION MOTOR CONTROLS
  	if(joy1Btn(7)) { // joy1Btn(7) is the right trigger
  		motor[motorD] = BALLCOLLECTION_onSpeed; // motor[motorD] is the ball collection motor
  	}
  	else {
  		motor[motorD] = BALLCOLLECTION_offSpeed; // motor[motorD] is the ball collection motor
  	}

  	
  	// GOAL LATCH CONTROLS
  	if(joy1Btn(0)) { // joy1Btn(0) is the "X" button
  		GOALLATCH_latchDown = !GOALLATCH_latchDown;
	  }
	  
  	if(GOALLATCH_latchDown) {
  		servo[servo1] = GOALLATCH_upPosition; // servo[servo1] is the goal latch
 	 	}
 	 	else {
 	 		servo[servo1] = GOALLATCH_downPosition; // servo[servo1] is the goal latch
 	 	}
  }
}
