#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    centerServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    sideServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
MotorD = Spinning Test motor
MotorE = Right side drive motors
MotorF = Left side drive motors
MotorG = Flywheel Motors
MotorH = Lift
*/

#include "JoystickDriver.c"

int threshold = 15;
int outerServoDownAngle = 100;
int outerServoUpAngle = 250;
int innerServoDownAngle = 50;
int innerServoUpAngle = 175;
int max(int a, int b) {
    int c = a - b;
    int k = (c >> 31) & 0x1;
    int max = a - k * c;
    return max;
}

int robotSpeedL = 0;
int robotSpeedR = 0;
bool innerServoDown = false;
bool outerServoDown = false;
bool ljb_new = true;
bool rjb_new = true;
int joyVal = 0;

task main() {
	while(true) {
		getJoystickSettings(joystick);

    // I. Steering
		// Part 1: Speed
		if(joy1Btn(8) == 1 && joy1Btn(7) == 0) {
			robotSpeedL = 100;
			robotSpeedR = 100;
		}
		else if(joy1Btn(7) == 1 && joy1Btn(8) >= 0) {
			robotSpeedL = -100;
			robotSpeedR = -100;
		}
		else if(joy1Btn(8) == 1 && joy1Btn(7) == 1) {
			robotSpeedL = 50;
			robotSpeedR = 50;
		}
		else {
			robotSpeedL = 0;
			robotSpeedR = 0;
		}
		// Part 2: Steering
		if(abs(joystick.joy1_x1) >= threshold) {
			if(joystick.joy1_x1 > 0) { // When > 0, joystick is left
				robotSpeedL = robotSpeedL - (abs(joystick.joy1_x1) - 15); // -15 to threshold jump
			}
			else { // Joystick is right
				robotSpeedR = robotSpeedR - (abs(joystick.joy1_x1) - 15); // -15 to threshold jump
			}
		}
		// II. Servos
		if(joy1Btn(11)) { // Left joystick button (for outer latch)
			if(ljb_new) {
				outerServoDown = !outerServoDown;
			}
		}
		else {
			ljb_new = true;
		}
		
		if(joy1Btn(12)) { // Right joystick button (for inner latch)
			if(rjb_new) {
				innerServoDown = !innerServoDown;
			}
		}
		else {
			rjb_new = true;
		}
		// III. Assign values to motors and servos
		// Part 1. Motors
		motor[motorE] = robotSpeedR;
		motor[motorF] = robotSpeedL;
		
		// Part 2. Servos
 	  if(outerServoDown) {
 	  	servo[sideServo] = outerServoDownAngle; //Set servo value for lowered position
 		}
 		else {
 			servo[sideServo] = outerServoUpAngle; //Set servo value for up position
 		}
		
		if (innerServoDown) {
  	  servo[centerServo] = innerServoDownAngle;  //Set Servo value for Lowered position
 	 	}
 		else {
 	    servo[centerServo] = innerServoUpAngle;  //Set servo value for Up position
 	  }
 	  // IV. 2nd joystick
 	  // Part 1: Flywheel
  	if(joy2Btn(8)) {
  		motor[motorG] = 100; //Sets flywheel to 100% power
  	}
  	else { // I am not messing with this else condition. Ctrl+C, ctrl+V, move on.
  		while(motor[motorG] > 1) {
  			motor[motorG] = motor[motorG] - 1;
  			delay(1);
  		}
  		if (motor[motorG] == 1) {
  			delay(900);
  		}
  		motor[motorG] = 0;
  	}
  	// Part 2: Ball collector
  	if(joy2Btn(7)) {
  		motor[motorD] = 75; //Sets ball collector to 75% power
	  }
	  else {
	  	motor[motorD] = 0;
		}
		// Part 3: Lift
		if(max(abs(joystick.joy2_y1), abs(joystick.joy2_y1)) > threshold) {
			if(max(abs(joystick.joy2_y1), abs(joystick.joy2_y1)) == abs(joystick.joy2_y1)) {
				joyVal = joystick.joy2_y1;
			}
			else {
				joyVal = joystick.joy2_y2;
			}
			motor[motorH] = joyVal;
		}
	}
}
